---
title: "Homework 01 - STAT416"
author: "Joseph Sepich (jps6444)"
date: "09/08/2020"
output:
  pdf_document:
    number_sections: false
---

# Chapter 1 Problem 4

Let $E, F, G$ be three events. Find expressions for the events.

## Part a

Only $F$ occurs:

\[E^c \cap F \cap G^c\]

## Part b

Both $E$ and $F$ but not $G$ occur:

\[(E \cup F) \cap G^c\]

## Part c

At least one event occurs:

\[E \cup F \cup G\]

## Part d

At least two events occur:

\[(E \cap F) \cup(E \cap G) \cup (F \cap G)\]

## Part e

All three events occur:

\[E \cap F \cap G\]

## Part f

None occurs:

\[(E \cup F \cup G)^c\]

## Part g

At most one occurs (Also the complement of at least two):

\[((E \cap F) \cup(E \cap G) \cup (F \cap G))^c\]

## Part h

At most two occur (Also the complement of all three):

\[(E \cap F \cap G)^c\]

# Chapter 1 Problem 11

If two fair dice are tossed, what is the probability that the sum is $i, i = 2, 3, ... 12$.

Recall the pmf of a single die. The likelihood of each digit is $p(x) = \frac16$. Since each digit has an equal likelihood of returning, we only have to count the total number of ways to sum to $i$ and then divide by the total number of combinations $6 * 6 = 36$ (size of sample space) to get the probability of the event to be that sum.

For example, for i = 7, we have 2 ways to get 1 and 6, 2 ways to get 2 and 5, and 2 ways to get 3 and 4. This would give i = 7 6 instances out of 36 total instances for a $p(i) = \frac16$.

| i | p(i) |
|---|------|
| 2 | $\frac{1}{36}$|
| 3 | $\frac{2}{36} = \frac{1}{18}$|
| 4 | $\frac{3}{36} = \frac{1}{12}$|
| 5 | $\frac{4}{36} = \frac19$|
| 6 | $\frac{5}{36}$|
| 7 | $\frac{6}{36} = \frac16$|
| 8 | $\frac{5}{36}$|
| 9 | $\frac{4}{36} = \frac19$|
|10 | $\frac{3}{36} = \frac{1}{12}$|
|11 | $\frac{2}{36} = \frac{1}{18}$|
|12 | $\frac{1}{36}$|

We can see that the pmf outline above is valid, because all probabilities are between 0 and 1, and the sum of all probabilities is 1.


# Chapter 1 Problem 20

Three dice are thrown. What is the probability the same number appears on exactly two of the three dice?

To solve this we can look at a sub event: the probability of a one appearing on exactly two of the three dice.

There is exactly $\frac16$ ways for two of the dice to land on 1 and there is exactly $\frac56$ ways for the third die to land in order to not land on the same number. This gives us a probability of $\frac16*\frac16*\frac56 = \frac{5}{216}$ of exactly two to land on one. We can multiply the probabilities like this, because the events are independent.

Since this is the exact same case for each of the six digits we can multiply the value we found by 6, or add it together six times:

\[p(x) = 6*\frac{5}{216} = \frac{15}{108}\]

# Chapter 1 Problem 21

Suppose that 5 percent of men and 0.25 percent of women are colorblind. A randomly chosen person is colorblind. What is the probability of this person being a male? Assume that there are an equal number of males and females.

Problem Constraints:

* $M := \text{Is a Male}$ 
* $B := \text{Is Colorblind}$
* $P(B | M) = 0.05$
* $P(B | M^c) = 0.0025$
* $P(M) = 0.5$

We want to find $P(M | B)$. For this we can use Bayes Theorem.

\[P(M|B) = \frac{P(B|M)P(M)}{P(B)}\]

The law of total probability will give us:

\[P(B) = P(B|M)P(M) + P(B|M^c)P(M^c) = 0.05*0.5 + 0.0025 * 0.5 = 0.02625\]

We can take this back to solve:

\[P(M|B) = \frac{0.05 * 0.5}{0.02625} = 0.9524\]

We can conclude that the probability of a randomly chosen person being a male, given that they are colorblind, is 95.24%.

# Chapter 1 Problem 26

A deck of 52 playing cards, containing 4 aces, is randomly divided into 4 piles of 13 cards each. Define events $E_1, E_2, E_3, \text{and} E_4$ such that each pile has $E_i$ has exactly 1 ace. Find the probability that each pile has an ace: $P(E_1E_2E_3E_4)$.

\[P(E_1E_2E_3E_4) = P(E_1)P(E_2|E_1)P(E_3|E_1E_2)P(E_4|E_1E_2E_3)\]

$P(E_1) = \frac{\binom41\binom{48}{12}}{\binom{52}{13}}$, since we have the sample space of choosing 13 cards from 52 cards, but only want to consider the instances where we draw 1 ace and 12 non-ace cards. We can continue this for each probability to get:

\[P(E_1)P(E_2|E_1)P(E_3|E_1E_2)P(E_4|E_1E_2E_3)=\frac{\binom41\binom{48}{12}}{\binom{52}{13}} \frac{\binom31\binom{36}{12}}{\binom{39}{13}} \frac{\binom21 \binom{24}{12}}{\binom{26}{13}} \frac{\binom11 \binom{12}{12}}{\binom{13}{13}}\]

```{r}
p_e_1 <- choose(4, 1) * choose(48, 12) / choose(52, 13)
p_e_2 <- choose(3, 1) * choose(36, 12) / choose(39, 13)
p_e_3 <- choose(2, 1) * choose(24, 12) / choose(26, 13)
p_e_4 <- choose(1, 1) * choose(12, 12) / choose(13, 13)

p_e_1 * p_e_2 * p_e_3 * p_e_4
```

\[P(E_1E_2E_3E_4) \approx 0.1055 \]

The probability of each pile having an ace is approximately **10.55%**.

# Chapter 1 Problem 29

Suppose that $P(E) = 0.6$. What can you say about $P(E | F)$?

## Part a

If events $E$ and $F$ are mutually exculusive, then we know that $P(E\cap F) = 0$ by definition of disjoint events. We can plug this into the formula of conditional probability:

\[P(E | F) = \frac{P(E \cap F)}{P(F)} = \frac{0}{P(F)} = 0\]

## Part b

If $E \subset F$, then $P(E \cap F) = P(E) = 0.6$, so we can say that

\[P(E | F) = \frac{P(E)}{P(F)} = \frac{0.6}{P(F)}; 0 <P(E|F) \leq1\]

## Part c

If $F \subset E$, then $P(E \cap F) = P(F)$, so we can say that

\[P(E | F) = \frac{P(E \cap F)}{P(F)} = \frac{P(F)}{P(F)} = 1\]

# Chapter 1 Problem 38

Urn 1 contains two white balls and one black ballm, while urn 2 contains one white ball and five black balls. one ball id drawn at random from urn 1 and placed in urn 2. A ball is then drawn from urn 2. It happens to be white. What is the probability that the transferred ball was white?

Problem Constraints

* $W_1 := \text{White ball transferred}$
* $W_2 := \text{White ball chosen from urn 2}$
* $P(W_1) = \frac23$

We want to find $P(W_1 | W_2)$. To find this we can use Bayes theorem:

\[P(W_1 | W_2) = \frac{P(W_2 | W_1)}{P(W_2)}\]

\[P(W_2) = P(W_2 | W_1)P(W_1)+ P(W_2|W_1^c)P(W_1^c) = \frac27\frac23 + \frac17\frac13 = \frac{5}{21}\]

\[P(W_1 | W_2) = \frac{\frac27\frac23}{\frac5{21}} = \frac{\frac4{21}}{\frac5{21}} = \frac45 = 0.8\]

We can say that if the ball pulled from urn 2 is white, then the probability that the transferred ball was white is **80%**.

# Chapter 1 Problem 42

There are three coins in a box. One is a two-headed coin ($i = 1$), another is a fair coin ($i = 2$), and the third is a biased coin that comes up heads 75% of the time ($i = 3$). When one of the three coins is selected at random and flipped, it shows heads. What is the probability that it was the two-headed coin?

Problem constraints:

* $C_i := \text{Coin i was flipped}$
* $P(H | C_1) = 1$
* $P(H | C_2) = 0.5$
* $P(H | C_3) = 0.75$

We want to find $P(C_1 | H)$. We can use Bayes theorem:

\[P(C_1 | H) = \frac{P(H|C_1)P(C_1)}{P(H)}\]

\[P(H) = P(H|C_1)P(C_1) + P(H|C_2)P(C_2) + P(H|C_3)P(C_3) = \frac13+\frac12\frac13+\frac34\frac13 = \frac9{12} =\frac34\]

Plugging this value back into the Bayes Theorem formula we get:

\[P(C_1 | H) = \frac{\frac13}{\frac34} = \frac49\]

Given that the random coin chosen resulted in a heads flip, there is a $\frac49 \approx 44.44$% chance that the coin was the two-headed coin.

# Chapter 1 Problem 46

Three prisoners are informed by their jailer that one of them has been chosen at random to be executed, and the other two are to be freed. Prisoner A asks the jailer to tell him privately which of his fellow prisoners will be set free, claiming that there would be no harm in divulging the information, wince he already knows that at leaste one will go free. The jailer refuses to answer this question, pointing out that if A knew which of his fellows were to be set free, then his own probability of being executed would rise from $\frac13$ to $\frac12$, since he would then be one of two prisoners. What do you think of the jailer's reasoning?

I think that the jailer's reasoning is spot on. Without divulging any information prisoner A knows that 1 out of 3 people will be executed, but he doesn't know which. If prisoner A knows who of the others will be set free, then he now knows that 1 out of 2 people will be executed, but doesn't know which. By being told who will be set free, the total sample space is shrunk from 3 to 2 for the executed prisoner to be chosen.

# Chapter 2 Problem 5

In this exercise we have a fair die that is rolled twice. We will calculate the probabilities associated with various random variables.

## Part a

Calculate the probabilities for a random variable that takes on the value of the maximum value to appear in the two rolls.

For each number one through six, the first roll, or the second roll would have to be the max value, and the other roll would have to be that value or less. For example, if 2 was the max value, the first or second roll would take on 2, but the other could take on 1 or 2. This gives us {(2,1), (2,2), or (1,2)} or three possibilities for a max of 2 versus 1 for a max of one. This pattern continues as the numbers grow, so 5 events for a max of 3, 7 for 4, 9 for 5, and 11 for 6. This gives us the following pmf.

| i | p(i) |
|---|------|
| 1 | $\frac{1}{36}$|
| 2 | $\frac{3}{36}$|
| 3 | $\frac{5}{36}$|
| 4 | $\frac{7}{36}$|
| 5 | $\frac{9}{36}$|
| 6 | $\frac{11}{36}$|

## Part b

Calculate the probabilites for a random variable that takes on the value of the minimum value to appear in the two rolls.

The pmf for this random variable mirrors that of the previous (that represented the maximum value), which gives us the following pmf:

| i | p(i) |
|---|------|
| 1 | $\frac{11}{36}$|
| 2 | $\frac{9}{36}$|
| 3 | $\frac{7}{36}$|
| 4 | $\frac{5}{36}$|
| 5 | $\frac{3}{36}$|
| 6 | $\frac{1}{36}$|

## Part c

Calculate the probabilities for the random variable of the sum of the two rolls.

This was already completed in problem 11 for chapter 1. The pmf is listed below, but look back at 1.11 for the reasoning.

| i | p(i) |
|---|------|
| 2 | $\frac{1}{36}$|
| 3 | $\frac{2}{36} = \frac{1}{18}$|
| 4 | $\frac{3}{36} = \frac{1}{12}$|
| 5 | $\frac{4}{36} = \frac19$|
| 6 | $\frac{5}{36}$|
| 7 | $\frac{6}{36} = \frac16$|
| 8 | $\frac{5}{36}$|
| 9 | $\frac{4}{36} = \frac19$|
|10 | $\frac{3}{36} = \frac{1}{12}$|
|11 | $\frac{2}{36} = \frac{1}{18}$|
|12 | $\frac{1}{36}$|

## Part d

Calculate the probabilities for the random variable for the value of the first roll minus the value of the second.

To create this pmf we can observe the pattern in the events in the sample space. The value of the random variable when the first die is a 1 ranges from 0 to -5, then when the first die is a 2 it ranges from 1 to -4, and so on. This gives us the following pmf (note that this pmf is similar to the sum RV pmf, with a difference in values):

| i | p(i) |
|---|------|
| 5 | $\frac{1}{36}$|
| 4 | $\frac{2}{36} = \frac{1}{18}$|
| 3 | $\frac{3}{36} = \frac{1}{12}$|
| 2 | $\frac{4}{36} = \frac19$|
| 1 | $\frac{5}{36}$|
| 0 | $\frac{6}{36} = \frac16$|
|-1 | $\frac{5}{36}$|
|-2 | $\frac{4}{36} = \frac19$|
|-3 | $\frac{3}{36} = \frac{1}{12}$|
|-4 | $\frac{2}{36} = \frac{1}{18}$|
|-5 | $\frac{1}{36}$|

# Chapter 2 Problem 9

Calculate the pmf of X using the given CDF.

X is a discrete random variable that can take on the following values. These values are the first value domain of each piece of the piecewise CDF:

\[x \in \{0, 1, 2, 3, 3.5\}\]

For each value we can use the following method:

\[p(x_i) = F(x_i) - F(x_{i-1})\]

So we get:

\[p(0) = F(0) = \frac12 \]
\[p(1) = F(1) - F(0) = \frac35 - \frac12 = \frac1{10}\]
\[p(2) = F(2) - F(1) = \frac45 - \frac35 = \frac15\]
\[p(3) = F(3) - F(2) = \frac9{10} -\frac45 = \frac1{10}\]
\[p(3.5) = F(3.5) - F(3) = 1 - \frac9{10} = \frac1{10}\]

# Chapter 2 Problem 10
