---
title: "Homework 05 - STAT416"
author: "Joseph Sepich (jps6444)"
date: "10/06/2020"
output:
  pdf_document:
    number_sections: false
---

# Chapter 4 Problem 5

We are given both the initial probability of starting at state $i$ along with the 1 step transition probability matrix. We can use both of these to determine $P(X_3) = \alpha P^3$.

$$
\alpha_1 = \alpha_0 P=\begin{bmatrix}\frac14 & \frac14 & \frac12\end{bmatrix}\begin{bmatrix}
\frac12 & \frac 13 & \frac16 \\
0 & \frac13 & \frac23 \\
\frac12 & 0 & \frac12
\end{bmatrix} = \begin{bmatrix}
\frac38 & \frac16 & \frac{11}{24}
\end{bmatrix}
$$

$$
\alpha_2 = \alpha_1 P=\begin{bmatrix}\frac38 & \frac16 & \frac{11}{24}\end{bmatrix}\begin{bmatrix}
\frac12 & \frac 13 & \frac16 \\
0 & \frac13 & \frac23 \\
\frac12 & 0 & \frac12
\end{bmatrix} = \begin{bmatrix}
\frac5{12} & \frac{13}{72} & \frac{29}{72}
\end{bmatrix}
$$

$$
\alpha_3 = \alpha_2 P=\begin{bmatrix}\frac5{12} & \frac{13}{72} & \frac{29}{72}\end{bmatrix}\begin{bmatrix}
\frac12 & \frac 13 & \frac16 \\
0 & \frac13 & \frac23 \\
\frac12 & 0 & \frac12
\end{bmatrix} = \begin{bmatrix}
\frac{59}{144} & \frac{43}{216} & \frac{169}{432}
\end{bmatrix}
$$

\[E[X_3] = 0 + \frac{43}{216} + \frac{169}{216} = \frac{212}{216} \approx 0.9815\]

# Chapter 4 Problem 8

## Part c

To find the probability that the second ball selected is red we need to know the probability of the state at time 2 (from which the ball will be selected). We use our initial probabilities combined with our transition probability matrix:

$$
\alpha_2 = \alpha_1 P=\begin{bmatrix}0 & 1 & 0\end{bmatrix}\begin{bmatrix}
0.5 & 0.5 & 0 \\
0.15 & 0.6 & 0.25 \\
0 & 0.3 & 0.7
\end{bmatrix} = \begin{bmatrix}
0.15 & 0.6 & 0.25
\end{bmatrix}
$$

So the probability of drawing a red ball second when there is 0 red balls is 0, 0.5 when there is 1 red ball, and 1 when there is 2 red balls. This gives us the probability $0 * 0.15 + 0.5 * 0.6 + 1 * 0.25 = 0.25 + 0.3 = 0.55$. The probability of selecting a red ball second is **55%**.

## Part d

Calculating the probability of selecting a red ball fourth follows the same logic as the previous part. We can pickup with $\alpha_2$.

$$
\alpha_3 = \alpha_2 P=\begin{bmatrix}0.15 & 0.6 & 0.25\end{bmatrix}\begin{bmatrix}
0.5 & 0.5 & 0 \\
0.15 & 0.6 & 0.25 \\
0 & 0.3 & 0.7
\end{bmatrix} = \begin{bmatrix}
0.165 & 0.51 & 0.325
\end{bmatrix}
$$
$$
\alpha_4 = \alpha_3 P=\begin{bmatrix}0.165 & 0.51 & 0.325\end{bmatrix}\begin{bmatrix}
0.5 & 0.5 & 0 \\
0.15 & 0.6 & 0.25 \\
0 & 0.3 & 0.7
\end{bmatrix} = \begin{bmatrix}
0.159 & 0.486 & 0.355
\end{bmatrix}
$$

This gives us the probability $0 * 0.159 + 0.5 * 0.486 + 1 * 0.355 = 0.243 + 0.355 = 0.598$. The probability of selecting a red ball fourth is **59.8%**. It makes sense that the likelihood of selecting red goes up with time as you are more likely to replace a red ball with a red ball while replace blue ball has equal probability for each.

# Chapter 4 Problem 10

# Chapter 4 Problem 15

# Chapter 4 Problem 16

# Problem A

# Problem B
















