---
title: "Homework 09 - STAT416"
author: "Joseph Sepich (jps6444)"
date: "11/17/2020"
output:
  pdf_document:
    number_sections: false
---

# Problem 21

Problem Constraints

* server $i; i \in (1,2)$
* service times: Exp$(\mu_i)$
* servuce acts as queue (first 1 then 2)
* you enter with server 1 busy

Since an exponential distribution is memoryless we do not need to know how long the first server is busy before we arrived. The total amount of time spent in the system will be the time spent in service with server 1 and then with server 2. If server 2 is slower than server 1 when you are served then you must wait for server 2 to finish before transferring. Our total time is defined as the summation of:

1. Expected waiting time for server 1
2. Expected time until next completed server
3. Expected remaining time (wait + served by 2)

The first quantity is merely the expected value of an exponential distribution: $E[W_1] = E[X_1] = \frac{1}{\mu_1}$. The second quantity we want to find the minimum of the two servers. This we defined as the exponential random variable with the sum of parameters $\mu_1 + \mu_2$. This gives the expected wait time of $E[W_2] = E[min(X_1+X_2)] = E[Z] = \frac{1}{\mu_1+\mu_2}$

The third quantity has two cases, which correponds to who finished first. If server 2 finishes first, then we expect to wait the amount of time the first server has left (memoryless, so its just the expectation) plus the expected amount of time of server 2. If server 2 finishes last, then we must wait for server 2 twice, which is merely the expected time of server 2 to finish twice. This gives us the following value:

\[E[W_3] = E[W_3|X_1<X_2]P(X_1<X_2)+E[W_3|X_2<X_1]P(X_2<X_1)\]
\[E[W_3] = (\frac{2}{\mu_2})\frac{\mu_1}{\mu_1+\mu_2}+(\frac{1}{\mu_1}+\frac{1}{\mu_2})\frac{\mu_2}{\mu_1+\mu_2}\]

This gives us our overall expected time in the system:

\[E[W] = E[W_1] + E[W_2] + E[W_3]\]
\[E[W] = \frac{1}{\mu_1} + \frac{1}{\mu_1+\mu_2} + (\frac{2}{\mu_2})\frac{\mu_1}{\mu_1+\mu_2}+(\frac{1}{\mu_1}+\frac{1}{\mu_2})\frac{\mu_2}{\mu_1+\mu_2}\]
\[E[W] = \frac{2}{\mu_1} + \frac{1}{\mu_1+\mu_2} + \frac{2\mu_1}{\mu_2(\mu_1+\mu_2)}\]

# Problem 30

Problem Constraints

* Cat and Dog
* Lifetime are exponential with rate $\lambda_i;i=c,d$

We must find the addtional lifetime of one pet, given the other has died.

\[E[L] = E[L_c|D=d]P(X_d<X_c)+E[L_d|D=c]P(X_c<X_d)\]
\[E[L] = \frac{1}{\lambda_c}\frac{\lambda_d}{\lambda_c+\lambda_d}+\frac{1}{\lambda_d}\frac{\lambda_c}{\lambda_c+\lambda_d}\]
\[E[L] = \frac{\lambda_d\lambda_d}{\lambda_d\lambda_c(\lambda_c+\lambda_d)}+\frac{\lambda_c\lambda_c}{\lambda_c\lambda_d(\lambda_c+\lambda_d)}\]
\[E[L] = \frac{\lambda_c^2+\lambda_d^2}{\lambda_c\lambda_d(\lambda_c+\lambda_d)}\]

# Problem 34

Problem Constraints

* A and B need kidneys (ordered A then B)
* death occurs Exp($\mu_i$)
* kidneys arrive Poisson($\lambda$)

## Part a

A will receive a kidney if A lives longer than the amount of time before the first kidney arrives.

\[P(\text{A gets kidney}) = P(T_1 <X_A)\]

From lemma 5.2 we know that $T_1$ is exponentially distributed with rate $\lambda$. Therefore we can use our known formula for comparing two exponential random variables:

\[P(T_1 <X_A) = \frac{\lambda}{\lambda + \mu_A}\]

## Part b

B will receive a kidney in two cases. A dies first and the first kidney comes before B dies or two kidneys arrive before either person dies. These can be described using the minimum of the three exponential random variables $T_1,X_A,X_B$, which is an exponential random variables with rate $\lambda+\mu_A+\mu_b$. (Note that we use Proposition 5.4 to expand the exponential distributed R.V. to $T_2$).

\[P(\text{B gets kidney})=P(T_1<X_B)P(X_A=min(T_1,X_A,X_B))+P(T_2<X_B)P(T_1=min(T_1,X_A,X_B))\]
\[P(\text{B gets kidney})=\frac{\lambda}{\lambda+\mu_B}\frac{\mu_A}{\lambda+\mu_A+\mu_B}+\frac{\lambda}{\lambda+\mu_b}\frac{\mu_A}{\lambda+\mu_A+\mu_B}\]
\[P(\text{B gets kidney})=(\frac{\lambda}{\lambda+\mu_B})(\frac{\lambda+\mu_A}{\lambda+\mu_A+\mu_B})\]

## Part c

Both A and B will not receive a kidney if the first kidney arrives after they both dies. This means we want to determine the probability:

\[P(X_A,X_B<T_1) = P(X_A<T_1)P(X_B<T_1) = \frac{\mu_A}{\lambda+\mu_A}\frac{\mu_B}{\lambda+\mu_B}\]

## Part d

Both A and B will receive new kidneys if the first kidney arrives before A dies and the second kidney arrives before B dies:

\[P(\text{Both get kidney}) = P(T_2<X_B)P(T_1=min(T_1,X_A,X_B)) =\frac{\lambda}{\lambda+\mu_b}\frac{\mu_A}{\lambda+\mu_A+\mu_B}\]

# Problem 35

# Problem 38

# Problem 39

# Problem 41

# Problem 43

# Problem 44
