---
title: "Homework 11 - STAT416"
author: "Joseph Sepich (jps6444)"
date: "12/10/2020"
output:
  pdf_document:
    number_sections: false
---

All questions come from Chapter 6.

# Problem 5

Problem Constraints

* N individuals
* Contact occurs with rate $\lambda$ (poisson)
* Contact equally likely to involve any $\binom{N}{2}$ people
* probability $p$ of infection (with infected and non-infected)
* $X(t)$ is number of infected people

## Part a

Yes, $X(t)$ is a continuous time Markov chain. The number of infected people only depends on the previous number of infected people and therefore satisfies the Markovian property. The number of infected people will only be one more than the previous number and depends on when a contact occurs.

## Part b

This Markov chain is a birth process. As time increases the state can only go from state i to state i + 1. Since the process can never decrease it is a pure birth process with $\mu_n=0$.

## Part c

With $X(0) = 1$ we want to determine the amount of time it takes for all N individuals to become infected. At time t we take 2 individuals that come into contact. There are $\binom{N}{2}$ possible pairs, but if the pair have the same status, then nothing happens to the state. If one and only one is infected then the other is infected as well and the state increases by one with probability p.

We can define our birth rate as a function of the rate of contact times the probability of infection times the probability of exactly one infected and one non-infected person being chosen.

\[\lambda_n = \lambda p\frac{i(N-i)}{\binom{N}{2}}\]

Since the time between infections are exponentially distributed with this rate $\lambda_n$ we can calcuate the mean time until total infection by summing the component means:

\[\Sigma_{i=1}^{N-1}\frac{1}{\lambda_n} = \frac{\binom{N}{2}}{\lambda p}\Sigma_{i=1}^{N-1}\frac{1}{i(N-i)}\]

# Problem 13

Problem Constraints

* Barbershop with 2 chairs
* Customers arrive Poisson process rate of 3 per hour
* Serving times Exponential with mean 1/4

To solve the questions model the process as a Markov chain with $X(t)$ representing the number of customers in the shop at time $t$. The state of this Markov chain can take on the values 0, 1, or 2, since the shop can serve a max of 2 customers.

## Part a

While we are below capacity $X(t) \in \{1, 2\}$ the state can increase by 1 with a rate of 3 per hour and while there are customers we can decrease the state by 1 with a rate of 4 per hour. We can use these rates in this M/M/1 queue. This gives us the balanced equations:

\[\pi_1 = \frac{3}{4}\pi_0\]
\[\pi_2 = \frac{3}{4}\pi_1\]

This results in the probabilities:

\[\pi_0=\frac{4^2}{4^3-3^3}\]
\[\pi_1=\frac{3*4}{4^3-3^3}\]
\[\pi_2=\frac{3^2}{4^3-3^3}\]

We can use these probabilities to find the average number of customers in the shop:

\[\overline{n} = 0\pi_0+1\pi_1+2\pi_2 = \frac{3*4}{4^3-3^3} + 2\frac{3^2}{4^3-3^3} \approx  0.811\]

The average number of customers in the barbershop in the long run is $0.811$.

## Part b

The proportion of potential customers that enter the shop is equal to the proportion of time the the shop is not at capacity. This is:

\[\pi_0+\pi_1 = \frac{4^2}{4^3-3^3} + \frac{3*4}{4^3-3^3} \approx 0.757\]

## Part c

We can find the additional amount of business by adjusting our system of equations for when the barber works double speed:

\[\pi_0=5\frac{8^2}{8^3-3^3}\]
\[\pi_1=\frac{3*40}{8^3-3^3}\]
\[\pi_2=5\frac{3^2}{8^3-3^3}\]

These new systems give the proportion of customers entering the shop to be:

\[5\frac{8^2}{8^3-3^3} +\frac{3*40}{8^3-3^3} \approx 0.907 \]

The shop has 90.7 percent of the potential customers entering the shop when working twice as fast versus 75.7 percent of customers. This is a roughly 19.8 percent increase in business.

# Problem 15

Problem Constraints

* two servers
* servers work at exponential rate 2
* customers arrive Poisson rate 3
* system capacity of 3

This problem can be modeled similarly to the previous problem on the barbershop, but instead there are now two servers as opposed to a single barber. That means this time we have a M/M/2/3 queue. This gives us the balanced equations:

\[3\pi_0 = 2\pi_1\]
\[3\pi_1 = 4\pi_2\]
\[3\pi_2 = 4\pi_3\]

Which can be updated to:

\[\pi_1 = \frac32\pi_0\]
\[\pi_2 = \frac34\pi_1 = \frac34\frac23\pi_0\]
\[\pi_3 = \frac34\pi_2 = \frac34\frac34\frac32\pi_0\]

This results in the probability for $\pi_3$:

\[\pi_3 = \frac{(\frac34)^2\frac32}{1 + \frac34 + (\frac34)^2 +(\frac34)^3}\]

## Part a

The fraction of potential customers that enter the system is equal to the fraction of time not spent at capacity. This is $1-\pi_3$:

\[1 - \frac{(\frac34)^2\frac32}{1 + \frac32 + \frac34\frac32 +(\frac34)^2\frac32}\]

## Part b

If there was a single server and his rate was twice as fast then we merely modify the first equation above to:

\[3\pi_0 = 4\pi_1\]

This yields a different value of $\pi_3$:

\[\pi_3 = \frac34\pi_2 = \frac34\frac34\frac34\pi_0\]

This gives us an updated value of:

\[1 - \frac{(\frac34)^3}{1 + \frac34 + (\frac34)^2 +(\frac34)^3}\]

# Problem 17

We can treat this as a continuous time Markov Chain with states 0, 1, and 2 where state 0 is when the machine is up, state 1 is when the machine is down due to type 1 failure, and state 2 is when the machine is down due to a type 2 failure. We can write the system of equations for the limiting probabilities:

\[\lambda\pi_0 = \mu_1\pi_1 + \mu_2\pi_2\]
\[\mu_1\pi_1 = \lambda\pi_0p\]
\[\mu_2\pi_2 =\lambda\pi_0(1-p)\]
\[\pi_0 + \pi_1 + \pi_2 = 1\]

We can solve this system:

\[\pi_1 = \frac{\lambda p \pi_0}{\mu_1}\]
\[\pi_2 = \frac{\lambda(1-p)\pi_0}{\mu_2}\]

Now to get $\pi_0$ we can solve $\pi_0 = 1 - \pi_1 - \pi_2$:

\[\pi_0 = 1 - \frac{\lambda p \pi_0}{\mu_1}  - \frac{\lambda(1-p)\pi_0}{\mu_2}\]

The proportion of time spent down due a type 1 failure is $\frac{\lambda p \pi_0}{\mu_1}$. The proportion of time spent down due to a type 2 failure is $\frac{\lambda(1-p)\pi_0}{\mu_2}$. The proportion of time spent up is the remaining proportion leftover after the sum of the proportion of time spent down: $1 - \frac{\lambda p \pi_0}{\mu_1}  - \frac{\lambda(1-p)\pi_0}{\mu_2}$.

# Problem 20

# Problem 21

# Problem 23

